# app/schemas/department.py
from pydantic import BaseModel, Field, field_validator
from typing import Optional
from app.schemas.base import TimeUserStampSchema


class DepartmentBase(BaseModel):
    name: str = Field(..., min_length=1, max_length=100)
    description: Optional[str] = None
    location: Optional[str] = Field(None, max_length=100)


class DepartmentCreate(DepartmentBase):
    """Create department - code is auto-generated from name"""
    class Config:
        extra = "forbid"


class DepartmentUpdate(BaseModel):
    name: Optional[str] = Field(None, min_length=1, max_length=100)
    description: Optional[str] = None
    location: Optional[str] = Field(None, max_length=100)
    # Note: code cannot be updated after creation
    
    class Config:
        extra = "forbid"


class DepartmentOut(DepartmentBase, TimeUserStampSchema):
    id: int
    code: str  # Read-only, generated by backend
    
    class Config:
        from_attributes = True


# For nested employee info in department responses
class EmployeeBasicForDepartment(BaseModel):
    """Basic employee info for nested department responses"""
    id: int
    first_name: str
    last_name: str
    email: str
    job_title: str
    name: str
    
    class Config:
        from_attributes = True


class DepartmentWithEmployees(DepartmentOut):
    """Department with list of employees"""
    employees: list[EmployeeBasicForDepartment] = []
    
    class Config:
        from_attributes = True


class PaginatedDepartments(BaseModel):
    count: int
    data: list[DepartmentOut]


class DepartmentListResponse(BaseModel):
    status: str
    result: PaginatedDepartments


class PaginatedDepartmentsWithEmployees(BaseModel):
    count: int
    data: list[DepartmentWithEmployees]


class DepartmentListWithEmployeesResponse(BaseModel):
    status: str
    result: PaginatedDepartmentsWithEmployees